### ISSUE TITLE
Scheduler task errorr

### ISSUE THREAD

**Issue by agendartobias** [xperseguers/t3ext-ig_ldap_sso_auth#105] opened 2020-07-23 07:53 UTC
Hey, when i try to add scheduler task for sync AD users i get this PHP error:

Fatal error: Declaration of Causal\IgLdapSsoAuth\Task\ImportUsers::getLanguageService() must be compatible with TYPO3\CMS\Scheduler\Task\AbstractTask::getLanguageService(): ?TYPO3\CMS\Core\Localization\LanguageService in C:\wamp64\www\htdocs\typo3conf\ext\ig_ldap_sso_auth\Classes\Task\ImportUsers.php on line 33

I am using TYPO3 10.4.4 and ig_ldap_sso_auth 3.5.1

Can anyone help?

**Comment by andremichaelis** [comment] 2020-08-12 19:27
Quickfix: 

/ig_ldap_sso_auth/Classes/Task/ImportUsers.php

Update lines 354 and following

`    /**
     * Returns the LanguageService.
     *
     * @return \TYPO3\CMS\Core\Localization\LanguageService|null
     */
    protected function getLanguageService(): ?\TYPO3\CMS\Core\Localization\LanguageService
    {
        return $GLOBALS['LANG'] ?? null;
    }
`

**Comment by andremichaelis** [comment] 2020-08-12 19:29
Quickfix:

Change lines 354 and following ...


```
    /**
     * Returns the LanguageService.
     *
     * @return \TYPO3\CMS\Core\Localization\LanguageService|null
     */
    protected function getLanguageService(): ?\TYPO3\CMS\Core\Localization\LanguageService
    {
        return $GLOBALS['LANG'] ?? null;
    }
```

**Comment by xperseguers** [comment] 2020-09-22 14:58
Duplicate of #101

**Closed by xperseguers** 2020-09-22 14:58 UTC
