### ISSUE TITLE
Update for TYPO3 v9

### ISSUE THREAD

**Issue by d3ntastic** [xperseguers/t3ext-ig_ldap_sso_auth#8] opened 2018-02-05 12:08 UTC
Do you have plans to migrate this extension to TYPO3 v9 (with PHP 7.2)? I would be happy, if you have.

**Comment by xperseguers** [comment] 2018-02-05 12:20
It will certainly be made compatible with TYPO3 v9 but #7 needs to be tackled first and is probably the (sole?) main problem making that a reality. Currently I don't need v9 support so I won't start it "for fun".

Regarding PHP 7.2, it possibly just work fine already.

**Comment by metaxos** [comment] 2018-03-27 13:27
@d3ntastic I have tried 424fd21 on a 8.7.12 running with a SQL-Server (not mySQL). Seems to work. We have issues importing fe_users and be_users, the groups are working.

![screen shot 2018-03-27 at 10 48 43](https://user-images.githubusercontent.com/5360113/37970242-3ba6fd54-31d3-11e8-8635-c77a36968ecc.png)

Any input why they should not be imported?

**Comment by tobikummer** [comment] 2018-11-29 13:46
Do you have an idea when we can expect TYPO3 9 compatibility? 🤔

**Comment by xperseguers** [comment] 2018-11-29 20:09
It will certainly be quicker if it gets sponsored one way or another since I wrote on February 5th that I did not plan to work on it for fun and I really don't have any need for v9 compatibility myself so it will not be done really soon, sorry.

**Comment by mathias-noethiger** [comment] 2018-11-30 11:58
Ok, how can we sponsor you?

**Comment by xperseguers** [comment] 2018-12-04 08:20
I don't think a whole crowdfunding project is necessary. Ideally, a few institutions are willing to participate and spend some money for the ~2 days needed to make it compatible in the form of an invoice.

**Comment by enterlight** [comment] 2018-12-06 14:41
Thanks for your work @xperseguers!  I think you have a nice lineup of eager beta testers for your extension on TYPO3 v9.  I am evaluating different CMS for a corporate intranet and while v8 didn't make the cut TYPOv9 would, if ldap extension was ready to go.  How can I contribute?

**Comment by sebeka** [comment] 2018-12-06 15:24
Hi, great Extension you made! Maybe @andreaswolf has a good starting point:
https://github.com/andreaswolf/t3ext-ig_ldap_sso_auth/tree/v9-compatibility

**Comment by masi** [comment] 2018-12-07 09:13
We at plan2net have cleaned up the patch done by @tritumRz. That is we have removed any superfluos changes (whitespace changes, reordering of use statements, etc.) so it's much easier to read for you. We don't have made a pull request yet as we have a small issue that needs to be fixed first.

Do you consider accepting a pull request without funding?

**Comment by xperseguers** [comment] 2018-12-07 23:15
sure, just need to double check and test as usual

**Comment by jackd248** [comment] 2019-03-21 10:27
Any updates to the TYPO3 v9 compatibility so far?

**Comment by xperseguers** [comment] 2019-03-21 10:28
Yes, good progress, please check the v9 branch

**Comment by MoppieMop** [comment] 2019-03-25 14:32
just tried your version (commits 1 hour ago).
But i get 
`
(1/1) #1294585866 InvalidArgumentException
No class named EXT:ig_ldap_sso_auth/Classes/Em/ConfigurationHelper.php:Causal\IgLdapSsoAuth\Em\ConfigurationHelper
`
I don't know why, because I find on this path the mentioned class.

**Comment by xperseguers** [comment] 2019-03-25 14:46
@MoppieMop on it, next time be sure to explain how to reproduce :)

**Comment by xperseguers** [comment] 2019-03-25 15:43
Branch `feature/TYPO3_v9` is considered functional enough (if not ready) to close this ticket.

**Closed by xperseguers** 2019-03-25 15:43 UTC

**Comment by Pit-Storm** [comment] 2019-04-25 11:31
Is it possible to sponsor it to bring it to a stable/master branch? How much time would it take?
