### ISSUE TITLE
Typo3 LTS 10: Style of toolbar broken

### ISSUE THREAD

**Issue by ffh-webadmin** [xperseguers/t3ext-ig_ldap_sso_auth#108] opened 2020-08-10 06:23 UTC
First thanks for this extension. We are using it since Typo3 6.2 and it is working great!

Within the current master of this extension and Typo3 10 LTS the CSS of the backend module toolbar is broken:

![ldap](https://user-images.githubusercontent.com/4989581/89756393-a261bd80-dae2-11ea-92f8-5b669a9a05e6.JPG)

It's not a main Issue, but perhaps easy to fix?

**Comment by xperseguers** [comment] 2020-09-22 15:18
Looks like it's "broken" since v8

**Comment by xperseguers** [comment] 2020-09-22 16:12
Ah... there are actually two problems here, one is about to get fixed, this is streamlining the toolbar with the rest of TYPO3 modules and the other is that indeed, I know that sometimes the CSS gets not included and IIRC this is somehow related to running in production mode instead of dev.

**Comment by xperseguers** [comment] 2020-09-22 16:43
I checked in "Live" mode but cannot reproduce :/ any idea of the root cause? Be sure to check with current master as I fixed details already.

**Comment by ffh-webadmin** [comment] 2020-09-23 06:47
Thanks! Just checked in poduction and dev mode on LTS 10. Looks fine in both cases.

**Comment by xperseguers** [comment] 2020-09-23 06:58
great!

**Closed by xperseguers** 2020-09-23 06:58 UTC
