### ISSUE TITLE
groups are not assigned to the users

### ISSUE THREAD

**Issue by medarob** [xperseguers/t3ext-ig_ldap_sso_auth#62] opened 2019-06-11 09:43 UTC
Hi,

I have a problem with the LDAP usergroups. It seems like that FE and BE usergroups are not assigned correctly to the users. I noticed that the following option is disable for FE and BE usergroups:
![grafik](https://user-images.githubusercontent.com/33951787/59260512-06b59280-8c3c-11e9-88b5-bad60cc788c4.png)

Do I have to activate this option in order to make this work? I'm not sure how to activate this option.

Here is my filter instruction and mapping instruction for FE users:
```(&(sAMAccountName={USERNAME})(employeeID=*))```

```
pid = 171
tstamp = {DATE}
email = <mail>
name = <cn>
first_name = <givenName>
last_name = <sn>
title = <title>
company = <company>
address = <streetAddress>
zip = <postalCode>
city = <l>
country = <countryCode>
telephone = <telephoneNumber>
usergroup = <memberOf>
```

But now, each user has 50 usergroups (FE) or 62 usergroups (BE) assigned but those are not the correct once. Normally only 4 to 20 groups are assigned to each user.

Does someone has an idea why this could happen?

TYPO3 8.7.26
LDAP 3.3.1

**Comment by fabtho** [comment] 2019-08-14 14:30
On the LDAP Tab you can switch this on "Extract groups from membership attribute"

![AwesomeScreenshot-intranet9-kshp-ch-typo3-index php-2019-08-14_4_30](https://user-images.githubusercontent.com/15102967/63029442-dcd55200-beb0-11e9-82d9-f11c6ee6f51d.png)

**Comment by ulrike-cosmoblonde** [comment] 2019-09-06 12:38
Hi, has this issue been solved?
I seem to have the same issue and it does not seem to be related to the group_membership setting.
I can retrieve users and groups (FE and BE) from my AD, but I can't get any groups assigned to my imported users.
With the FE- and BE-user mapping: usergroup = <memberOf> no group is assigned.

Using Typo3 v9.5.5.

Any help is much appreciated.

**Closed** 2019-10-29 08:31 UTC

**Comment by medarob** [comment] 2019-11-05 09:30
We updated the extension to 3.5 but the problem is still there. Every BE user has over 60 groups assigned.
![grafik](https://user-images.githubusercontent.com/33951787/68194678-b86faa00-ffb5-11e9-8948-d4a9c5d6ace3.png)

If I use the search functionality and search for that BE user it works. The memberof attribute has 23 groups listed.
![grafik](https://user-images.githubusercontent.com/33951787/68195165-a8a49580-ffb6-11e9-9462-aac2de7bca50.png)

(I also tried the previous fix mentioned but that didn't solved the problem.)

**Comment by xperseguers** [comment] 2019-11-05 09:34
@medarob Looks like the problem is not really that groups are not assigned, but that too many groups are assigned. Please open a new ticket and describe exactly what is the problem, making sure to explain for instance if the 23 groups that should be assigned are actually assigned among the "60+ groups" assigned or not, if you assign static groups as well, ... well everything step-by-step in order to reproduce this problem. Thanks.
